2021-01-13 20:50:30,547 DEBUG   MainThread:20902 [wandb_config.py:_load_defaults():132] no defaults not found in config-defaults.yaml
2021-01-13 20:50:30,552 DEBUG   MainThread:20902 [git_repo.py:repo():30] git repository is invalid
2021-01-13 20:50:30,554 DEBUG   MainThread:20902 [run_manager.py:__init__():546] Initialized sync for job-m-reload/3nuwov2r
2021-01-13 20:50:30,556 INFO    MainThread:20902 [run_manager.py:wrap_existing_process():1148] wrapping existing process 2006202021-01-13 20:50:31,554 INFO    Thread-3  :20902 [run_manager.py:_on_file_created():680] file/dir created: /home/jintao/CardinalityEstimationBenchmark/neurocard-master/neurocard/wandb/run-20210113_125029-3nuwov2r/wandb-met2021-01-13 2021-01-13 20:50:50,281 INFO    MainThread:20890 [run_manager.py:init_run():927] system metrics and metadata threa20212021-012021-01-13 20:50:50,282 INFO    MainThread:20890 [run_manager.py:wrap_existing_process():1165] informing user process we are ready 2021-01-13 2021-01-13 20:50:50,285 INFO    MainThread:20902 [run_manager.py:_sync_etc():1272] entering loop for messages from us20212021-01-13 20:50:50,781 INFO    MainThread:20889 [run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,781 INFO    MainThread:20889 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,781 INFO    MainThread:20889 [run_manager.py:shutdown():1071] shutting down system stats and metadata service
ts and metadata service
ile/dir created: /home/jintao/CardinalityEstimationBenchmark/neurocard-master/neurocard/wandb/run-20210113_125029-1utv0qw7/output.log
2021-01-13 20:50:31,479 INFO    Thread-3  :20897 [1dlfwypd:run_manager.py:_on_file_created():680] file/dir created: /home/jintao/CardinalityEstimationBenchmark/neurocard-master/neurocard/wandb/run-20210113_125029-1dlfwypd/wandb-metadata.json
2021-01-13 20:50:31,507 INFO    Thread-3  :20900 [1hnkcaj1:run_manager.py:_on_file_created():680] file/dir created: /home/jintao/CardinalityEstimationBenchmark/neurocard-master/neurocard/wandb/run-20210113_125029-1hnkcaj1/output.log
2021-01-13 20:50:31,508 INFO    Thread-3  :20901 [3sc61yzj:run_manager.py:_on_file_created():680] file/dir created: /home/jintao/CardinalityEstimationBenchmark/neurocard-master/neurocard/wandb/run-20210113_125029-3sc61yzj/output.log
2021-01-13 20:50:31,554 INFO    Thread-3  :20902 [3nuwov2r:run_manager.py:_on_file_created():680] file/dir created: /home/jintao/CardinalityEstimationBenchmark/neurocard-master/neurocard/wandb/run-20210113_125029-3nuwov2r/wandb-metadata.json
2021-01-13 20:50:45,285 INFO    MainThread:20888 [3unvzti2:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:45,286 INFO    MainThread:20888 [3unvzti2:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:45,286 INFO    MainThread:20888 [3unvzti2:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:46,715 INFO    MainThread:20888 [3unvzti2:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:46,716 INFO    MainThread:20888 [3unvzti2:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,281 INFO    MainThread:20897 [1dlfwypd:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,280 INFO    MainThread:20901 [3sc61yzj:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,281 INFO    MainThread:20889 [3a84b95n:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,281 INFO    MainThread:20900 [1hnkcaj1:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,281 INFO    MainThread:20899 [1utv0qw7:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,281 INFO    MainThread:20901 [3sc61yzj:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,281 INFO    MainThread:20900 [1hnkcaj1:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,281 INFO    MainThread:20897 [1dlfwypd:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,281 INFO    MainThread:20902 [3nuwov2r:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,281 INFO    MainThread:20890 [2buzcb2p:run_manager.py:init_run():927] system metrics and metadata threads started
2021-01-13 20:50:50,282 INFO    MainThread:20889 [3a84b95n:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,281 INFO    MainThread:20899 [1utv0qw7:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,282 INFO    MainThread:20902 [3nuwov2r:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,282 INFO    MainThread:20890 [2buzcb2p:run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2021-01-13 20:50:50,282 INFO    MainThread:20900 [1hnkcaj1:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,282 INFO    MainThread:20901 [3sc61yzj:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,282 INFO    MainThread:20889 [3a84b95n:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,282 INFO    MainThread:20897 [1dlfwypd:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,282 INFO    MainThread:20899 [1utv0qw7:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,282 INFO    MainThread:20890 [2buzcb2p:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,285 INFO    MainThread:20902 [3nuwov2r:run_manager.py:_sync_etc():1272] entering loop for messages from user process
2021-01-13 20:50:50,477 INFO    MainThread:20902 [3nuwov2r:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,477 INFO    MainThread:20902 [3nuwov2r:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,477 INFO    MainThread:20902 [3nuwov2r:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,502 INFO    MainThread:20900 [1hnkcaj1:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,502 INFO    MainThread:20900 [1hnkcaj1:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,503 INFO    MainThread:20900 [1hnkcaj1:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,503 INFO    MainThread:20901 [3sc61yzj:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,504 INFO    MainThread:20901 [3sc61yzj:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,504 INFO    MainThread:20901 [3sc61yzj:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,536 INFO    MainThread:20899 [1utv0qw7:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,547 INFO    MainThread:20899 [1utv0qw7:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,547 INFO    MainThread:20899 [1utv0qw7:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,759 INFO    MainThread:20890 [2buzcb2p:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,759 INFO    MainThread:20897 [1dlfwypd:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,759 INFO    MainThread:20890 [2buzcb2p:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,759 INFO    MainThread:20890 [2buzcb2p:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,759 INFO    MainThread:20897 [1dlfwypd:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,760 INFO    MainThread:20897 [1dlfwypd:run_manager.py:shutdown():1071] shutting down system stats and metadata service
2021-01-13 20:50:50,781 INFO    MainThread:20889 [3a84b95n:run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2021-01-13 20:50:50,781 INFO    MainThread:20889 [3a84b95n:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2021-01-13 20:50:50,781 INFO    MainThread:20889 [3a84b95n:run_manager.py:shutdown():1071] shutting down system stats and metadata service
